Module 4: School library, milestone 3
kamzzy/school_library_oop pull request #3
Opened 2022-07-28 20:03 UTC by kamzzy

### Commit details

- created a has-many and belong-to relationships between rental, person and book
- create a has-many relationship between classroom and student

2022-07-28 20:14 UTC, Ghiftee requested changes
## STATUS: CHANGES REQUIRED ♻️♻️
Hello 👋🏽 @kamzzy

Good job working on the project so far! 
✔️ Associations are set correctly
✔️ There are no linter errors
However, there are some issues that you need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/6inPKJhYJVBmxgADMA/giphy.gif)

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-07-28 20:14 UTC, Ghiftee commented on book.rb
> +  attr_reader :rentals
- [ ] Kindly add rentals to ```attr_accessor``` so that we cannot just read but also change it.

2022-07-28 20:14 UTC, Ghiftee commented on person.rb
> +  attr_reader :id, :rentals
- [ ] Kindly add rentals to ```attr_accessor``` so that we cannot just read but also change it.

2022-07-29 07:17 UTC, prolajumokeoni approved these changes
Hi @kamzzy, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
- No linter errors ✅ 
- Git flow was used correctly 🚀 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-29 14:59 UTC, merged